# Generated by Django 2.2 on 2020-02-01 21:19

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, help_text='文案内容', null=True, verbose_name='文案内容')),
                ('sign_starttime', models.DateTimeField(help_text='报名开始时间', verbose_name='报名开始时间')),
                ('sign_endtime', models.DateTimeField(help_text='报名结束时间', verbose_name='报名结束时间')),
                ('count', models.IntegerField(help_text='报名人数', verbose_name='报名人数')),
                ('group_maxcount', models.IntegerField(blank=True, help_text='最大队内人数', null=True, verbose_name='最大队内人数')),
                ('group_mincount', models.IntegerField(blank=True, help_text='最小队内人数', null=True, verbose_name='最小队内人数')),
                ('classes', models.IntegerField(choices=[(0, '单人赛'), (1, '团体赛')], help_text='比赛种类', verbose_name='比赛种类')),
            ],
            options={
                'verbose_name': '竞赛',
                'verbose_name_plural': '竞赛',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=120, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, help_text='新闻内容', null=True, verbose_name='新闻内容')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='流程名', max_length=100, verbose_name='流程名')),
                ('starttime', models.DateTimeField(help_text='流程开始时间', verbose_name='流程开始时间')),
                ('endtime', models.DateTimeField(help_text='流程结束时间', verbose_name='流程结束时间')),
            ],
            options={
                'verbose_name': '比赛流程',
                'verbose_name_plural': '比赛流程',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '比赛种类',
                'verbose_name_plural': '比赛种类',
            },
        ),
        migrations.CreateModel(
            name='UseAndMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.IntegerField(choices=[(0, '不是队长'), (1, '是队长')], default=1)),
                ('signtime', models.DateTimeField(default=datetime.datetime.now, help_text='报名时间', verbose_name='报名时间')),
                ('match', models.ForeignKey(help_text='比赛', on_delete=django.db.models.deletion.CASCADE, to='match.Match', verbose_name='比赛')),
            ],
        ),
    ]
