# Generated by Django 2.2 on 2020-02-02 11:32

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0002_auto_20200201_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='check',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核不通过')], default=0, help_text='审核状态', verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='match',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, help_text='竞赛内容', null=True, verbose_name='竞赛内容'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(default=datetime.datetime.now, help_text='评论时间', verbose_name='评论时间')),
                ('check', models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核不通过')], default=0, help_text='审核状态', verbose_name='审核状态')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, help_text='评论内容', null=True, verbose_name='评论内容')),
                ('user', models.ForeignKey(help_text='评论用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
