# Generated by Django 2.2 on 2020-02-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20200202_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='group_maxcount',
            field=models.IntegerField(default=0, help_text='最大队内人数', verbose_name='最大队内人数'),
        ),
        migrations.AlterField(
            model_name='match',
            name='group_mincount',
            field=models.IntegerField(default=0, help_text='最小队内人数', verbose_name='最小队内人数'),
        ),
    ]
