# Generated by Django 2.2 on 2020-02-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_useandmatch_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='useandmatch',
            name='check',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核不通过')], default=0, help_text='审核状态', verbose_name='审核状态'),
        ),
    ]
