# Generated by Django 2.2 on 2020-02-07 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20200206_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间'),
        ),
    ]
