# Generated by Django 2.2 on 2020-02-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_auto_20200207_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.ForeignKey(help_text='比赛类型', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='match.Type', verbose_name='比赛类型'),
        ),
    ]
